return {
    ACTIONS = {
        CASTSPELL = {
            INSERT = "Insert",
            PULLOUT = "Pull Out",
            SUICIDE = "Suicide",
        },
        MDODGE = "Dash",
        MDODGE2 = "Dodge",
    },
    CHARACTER_ABOUTME = {
        manutsawee = "Manutsawee is too long so just louis.",
    },
    CHARACTER_BIOS = {
        manutsawee = {
            {
                desc = "October 9",
                title = "Birthday",
            },
            {
                desc = "Learn Everything Technical College of Hawaii",
                title = "Current School",
            },
            {
                desc = "Unagi, Bacon and Eggs, Cooked Kelp Fronds, Durian, Roasted durian \nCaliforniaroll, Caviar \nSteamed Ham Sandwich, Tea, Ice Tea \nLiceloaf, Boomberry Pancakes",
                title = "Favorite Food",
            },
            {
                desc = "Manutsawee.",
                title = "Her Past...",
            },
            {
                desc = "Tokijin\nThe cursed sword made from the fangs of the Ghost of God is full of evil, and ordinary people can easily be controlled by it.\nIt was originally broken by Sesshomaru, but Louis found it in an abandoned shrine.. .",
                title = "Cursed Sword",
            },
        },
    },
    CHARACTER_DESCRIPTIONS = {
        manutsawee = "*Art of the Japanese sword\n*Brave\n*Benevolent",
    },
    CHARACTER_NAMES = {
        manutsawee = "Manutsawee",
    },
    CHARACTER_QUOTES = {
        manutsawee = "\"Where There's a Will, There's a Way\"",
    },
    CHARACTER_SURVIVABILITY = {
        manutsawee = "󰀕Grim",
    },
    CHARACTER_TITLES = {
        manutsawee = "The Red-Eyes Girl",
    },
    M_LOADINGTIPS = {
        TOKIJIN = "I can't suppress its evil spirit, I can't control tokijin -L",
    },
    NAMES = {
        BOAT_MSURFBOARD = "Louis's Surf board",
        HARAKIRI = "Harakiri",
        HITOKIRI = "Nihiru",
        HMINGOT = "Hot Mysterious Ingot",
        KATANABLADE = "Katana Blade",
        KATANABODY = "Katana shape",
        KOSHIRAE = "Sakakura",
        MAID_HB = "Louis's headwear",
        MANUTSAWEE = "Manutsawee",
        MFRUIT = "Louis's memory fruit",
        MINGOT = "Mysterious Ingot",
        MMIKO_ARMOR = "Miko Robe",
        MNAGINATA = "Naginata",
        MORTALBLADE = "Mortal Blade",
        MSURFBOARD_ITEM = "louis's Surf board",
        M_FOXMASK = "Kitsune Mask",
        M_SCARF = "Black Scarf",
        RAIKIRI = "Raikiri",
        SHINAI = "Shinai",
        SHIRASAYA = "Yasha",
        SHUSUI = "Shusui",
        TENSEIGA = "Tenseiga",
        TOKIJIN = "Tokijin",
        TRUE_HITOKIRI = "Nihiru The Bloodseeker",
        TRUE_KOSHIRAE = "Sakakura The Giant Slayers",
        TRUE_RAIKIRI = "Raikiri The Lightning Cutter",
        TRUE_SHIRASAYA = "Yasha The Demon Slayer",
        VSCODE = "Visual Studio Code",
        YARI = "Yari",
        M_PANTSU = "Blue and white striped pantsu",
        MOMO_HAT = "Erebus Crown",
        MOMO = "Momo",
    },
    RECIPE_DESC = {
        HARAKIRI = "Pay your mistake.",
        HITOKIRI = "The Bloodseeker",
        KATANABLADE = "Sharp katana blade",
        KOSHIRAE = "The Giant Slayers",
        MAID_HB = "Louis's headwear set.",
        MINGOT = "Bring it to fire",
        MMIKO_ARMOR = "Miko robe for miko skin",
        MNAGINATA = "It's Japanese Spear.",
        MORTALBLADE = "To cut the immortality.",
        MSURFBOARD_ITEM = "louis's Surf board",
        M_FOXMASK = "Fox Mask!",
        M_SCARF = "Black Scarf",
        RAIKIRI = "The Lightning Cutter",
        SHINAI = "Training Sword.",
        SHIRASAYA = "The Demon Slayer",
        SHUSUI = "A Legendary Sword of Wano.",
        TRUE_HITOKIRI = "True Nihiru",
        TRUE_KOSHIRAE = "True Sakakura",
        TRUE_RAIKIRI = "True Raikiri",
        TRUE_SHIRASAYA = "The Demon Slayer",
        VSCODE = "There is nothing that cannot be solved with one line of code.",
        YARI = "It's Japanese Spear.",
    },
    SKILL = {
        REFUSE_RELEASE = "I don't wanna do this.",
        SKILL1ATTACK = "ICHIMONJI",
        SKILL1START = "ICHI NO KATA!\n󰀈: ",
        SKILL2ATTACK = "HABAKIRI!!",
        SKILL2START = "NI NO KATA!\n󰀈: ",
        SKILL3ATTACK = "ONIKIRI!!",
        SKILL3START = "SAN NO KATA! \n󰀈: ",
        SKILL4ATTACK = "ISSHIN!!",
        SKILL4START = "SHI NO KATA!\n󰀈: ",
        SKILL5ATTACK = "SHINDEN ISSEN!!",
        SKILL5START = "GO NO KATA!\n󰀈: ",
        SKILL6ATTACK = "RYUSEN!!",
        SKILL6START = "ROKU NO KATA!\n󰀈: ",
        SKILL7ATTACK = "SUSANOO!!",
        SKILL7START = "SHICHI NO KATA!\n󰀈: ",
    },
    SKIN_DESCRIPTIONS = {
        manutsawee_bocchi = "Goto Hitori's sportswear from Bocchi The Rock",
        manutsawee_fuka = "Fu hua hawk of the fog's outfit from honkai impact 3d",
        manutsawee_jinbei = "Japan's outfit.",
        manutsawee_maid = "Maid's outfit",
        manutsawee_miko = "Japan's shrine maiden outfit.",
        manutsawee_none = "Thai's school uniform",
        manutsawee_qipao = "China's dress",
        manutsawee_sailor = "Japan's school uniform",
        manutsawee_shinsengumi = "Laws of the Shinsengumi\nOne must not infringe the samurai code\nOne is not authorized to escape from office\nOne is not allowed to arbitrarily raise money\nOne must not arbitrarily handle litigations\nOne is not authorized to engage in personal conflicts\n",
        manutsawee_taohuu = "Taohuu",
        manutsawee_uniform_black = "I'm Agent L.",
        manutsawee_yukata = "Japan's outfit mini version.",
        manutsawee_yukatalong = "Japan's outfit.",
        manutsawee_yukatalong_purple = "Japan's outfit purple version.",
    },
    SKIN_NAMES = {
        manutsawee_bocchi = "Guitar Hero",
        manutsawee_fuka = "Cosplay",
        manutsawee_jinbei = "Jinbei",
        manutsawee_maid = "Maid",
        manutsawee_miko = "Miko",
        manutsawee_none = "Louis",
        manutsawee_qipao = "Qipao",
        manutsawee_sailor = "Sailor Uniform",
        manutsawee_shinsengumi = "Shinsengumi",
        manutsawee_taohuu = "Taohuu",
        manutsawee_uniform_black = "MIB",
        manutsawee_yukata = "Kimono(M) ",
        manutsawee_yukatalong = "Kimono",
        manutsawee_yukatalong_purple = "Kimono(P)",
    },
    SKIN_QUOTES = {
        manutsawee_bocchi = "\"mu mu mu mu mu mu mu mu\"",
        manutsawee_fuka = "\"I'm a kung-fu master now.\"",
        manutsawee_jinbei = "\"Relax Feeling good.\"",
        manutsawee_maid = "\"I'm not a maid but i like this.\"",
        manutsawee_miko = "\"Can i fight with yokai?'\"",
        manutsawee_none = "I hate this uniform.",
        manutsawee_qipao = "\"Ni hao ..? Happy Lunar New Year!'\"",
        manutsawee_sailor = "\"So so so... nothing just say so..\"",
        manutsawee_shinsengumi = "\"One must not infringe the samurai code!\"",
        manutsawee_taohuu = "\"I'm cute, please give me money.\"",
        manutsawee_uniform_black = "\"It's because the light from Venus is reflected on...the swamp gas...so...\"",
        manutsawee_yukata = "\"Shine omae! haha.'\"",
        manutsawee_yukatalong = "\"Kon ni chi wa ..?'\"",
        manutsawee_yukatalong_purple = "\"Kon ni chi wa ..?'\"",
    },
    MOMO = {
        ONREFUSE = {
            LIST = {
                "Honey, don't make trouble, I don't need this.",
                "I just want something related to you, even memories",
                "Honey, Don't you know what I want?",
            },
            IRRELEVANT = "No, what does this have to do with you? I just want her to give it to me.",
        },
        ONNIGHT = {
            FORHONEY = "Don't worry, honey, I will turn on the light.",
            OFSELF = "Don't worry you can't see me.",
            SAMETIME = "Don't worry, honey, I will turn on the light."
        },
    },
    M_EPITAPHS = {
        -- These epitaphs reference lines spoken by the beggar in the film Kung Fu Hustle :P
        "\nHey, my friend, I see you have extraordinary talent, you are a rare genius.\nIt's up to you to maintain the peace of the underworld.\nI have a katana here called tenseiga.\nI see that you are destined for it, so I will give it to you directly, provided you can pick it up.",
        "\nWow, incredible!\nYou have a flash of inspiration bursting out of your head, you know?\nDespite your young age, you have remarkable aptitude.\nYou are a prodigy rarely seen even once in ten thousand years!\nAs the saying goes: If I don't enter the underworld, who will?\nI'll leave the task of maintaining peace in the underworld to you. Okay?\nThis Tensaiga is a priceless treasure.\nI see that we are fated, so I shall bestow it upon you, as long as you can lift it"
    },
}
