return {
{
    ACTIONS = {
        CASTSPELL = {
            INSERT = "Insert",
            PULLOUT = "Pull Out",
            SUICIDE = "Suicide",
        },
        MDODGE = "Dash",
        MDODGE2 = "Dodge",
    },
    CHARACTER_ABOUTME = {
        manutsawee = "Manutsawee is too long so just louis.",
    },
    CHARACTER_BIOS = {
        manutsawee = {
            {
                desc = "October 9",
                title = "Birthday",
            },
            {
                desc = "夏威夷什么都学技术学院",
                title = "就读学校",
            },
            {
                desc = "Unagi, Bacon and Eggs, Cooked Kelp Fronds, Durian, Roasted durian \nCaliforniaroll, Caviar \nSteamed Ham Sandwich, Tea, Ice Tea \nLiceloaf, Boomberry Pancakes",
                title = "Favorite Food",
            },
            {
                desc = "Manutsawee.",
                title = "Her Past...",
            },
            {
                desc = "斗鬼神\n使用悟心鬼的獠牙制成的诅咒之剑, 充满邪气, 一般人极易被其反控制.\n原被杀生丸折断, 但Louis在一所废弃的神社发现了它...",
                title = "诅咒之剑",
            },
        },
    },
    CHARACTER_DESCRIPTIONS = {
        manutsawee = "*Art of the Japanese sword\n*Brave\n*Benevolent",
    },
    CHARACTER_NAMES = {
        manutsawee = "Manutsawee",
    },
    CHARACTER_QUOTES = {
        manutsawee = "\"Where There's a Will, There's a Way\"",
    },
    CHARACTER_SURVIVABILITY = {
        manutsawee = "󰀕Grim",
    },
    CHARACTER_TITLES = {
        manutsawee = "The Red-Eyes Girl",
    },
    M_LOADINGTIPS = {
        TOKIJIN = "我无法压住它的邪气，无法驾驭斗鬼神 -L",
    },
    NAMES = {
        BOAT_MSURFBOARD = "Louis's Surf board",
        HARAKIRI = "Harakiri",
        HITOKIRI = "Nihiru",
        HMINGOT = "Hot Mysterious Ingot",
        KATANABLADE = "Katana Blade",
        KATANABODY = "Katana shape",
        KOSHIRAE = "Sakakura",
        KUROKATANA = "Kurokatana",
        MAID_HB = "Louis's headwear",
        MANUTSAWEE = "Manutsawee",
        MFRUIT = "Louis's memory fruit",
        MINGOT = "Mysterious Ingot",
        MMIKO_ARMOR = "Miko Robe",
        MNAGINATA = "Naginata",
        MORTALBLADE = "Mortal Blade",
        MSURFBOARD_ITEM = "louis's Surf board",
        M_FOXMASK = "Kitsune Mask",
        M_SCARF = "Black Scarf",
        RAIKIRI = "Raikiri",
        SHINAI = "Shinai",
        SHIRASAYA = "Yasha",
        SHUSUI = "Shusui",
        TOKIJIN = "Tokijin",
        TRUE_HITOKIRI = "Nihiru The Bloodseeker",
        TRUE_KOSHIRAE = "Sakakura The Giant Slayers",
        TRUE_RAIKIRI = "Raikiri The Lightning Cutter",
        TRUE_SHIRASAYA = "Yasha The Demon Slayer",
        YARI = "Yari",
    },
    RECIPE_DESC = {
        HARAKIRI = "Pay your mistake.",
        HITOKIRI = "The Bloodseeker",
        KATANABLADE = "Sharp katana blade",
        KOSHIRAE = "The Giant Slayers",
        KUROKATANA = "Japanese Sword.",
        MAID_HB = "Louis's headwear set.",
        MINGOT = "Bring it to fire",
        MMIKO_ARMOR = "Miko robe for miko skin",
        MNAGINATA = "It's Japanese Spear.",
        MORTALBLADE = "To cut the immortality.",
        MSURFBOARD_ITEM = "louis's Surf board",
        M_FOXMASK = "Fox Mask!",
        M_SCARF = "Black Scarf",
        RAIKIRI = "The Lightning Cutter",
        SHINAI = "Training Sword.",
        SHIRASAYA = "The Demon Slayer",
        SHUSUI = "A Legendary Sword of Wano.",
        TRUE_HITOKIRI = "True Nihiru",
        TRUE_KOSHIRAE = "True Sakakura",
        TRUE_RAIKIRI = "True Raikiri",
        TRUE_SHIRASAYA = "The Demon Slayer",
        YARI = "It's Japanese Spear.",
    },
    SKILL = {
        REFUSE_RELEASE = "I don't wanna do this.",
        SKILL1ATTACK = "ICHIMONJI",
        SKILL1START = "ICHI NO KATA!\n󰀈: ",
        SKILL2ATTACK = "HABAKIRI!!",
        SKILL2START = "NI NO KATA!\n󰀈: ",
        SKILL3ATTACK = "ONIKIRI!!",
        SKILL3START = "SAN NO KATA! \n󰀈: ",
        SKILL4ATTACK = "ISSHIN!!",
        SKILL4START = "SHI NO KATA!\n󰀈: ",
        SKILL5ATTACK = "SHINDEN ISSEN!!",
        SKILL5START = "GO NO KATA!\n󰀈: ",
        SKILL6ATTACK = "RYUSEN!!",
        SKILL6START = "ROKU NO KATA!\n󰀈: ",
        SKILL7ATTACK = "SUSANOO!!",
        SKILL7START = "SHICHI NO KATA!\n󰀈: ",
    },
    SKIN_DESCRIPTIONS = {
        manutsawee_fuka = "Fu hua hawk of the fog's outfit from honkai impact 3d",
        manutsawee_jinbei = "Japan's outfit.",
        manutsawee_maid = "Maid's outfit",
        manutsawee_miko = "Japan's shrine maiden outfit.",
        manutsawee_none = "Thai's school uniform",
        manutsawee_qipao = "China's dress",
        manutsawee_sailor = "Japan's school uniform",
        manutsawee_shinsengumi = "Laws of the Shinsengumi\nOne must not infringe the samurai code\nOne is not authorized to escape from office\nOne is not allowed to arbitrarily raise money\nOne must not arbitrarily handle litigations\nOne is not authorized to engage in personal conflicts\n",
        manutsawee_taohuu = "Taohuu",
        manutsawee_yukata = "Japan's outfit mini version.",
        manutsawee_yukatalong = "Japan's outfit.",
        manutsawee_yukatalong_purple = "Japan's outfit purple version.",
        manutsawee_uniform_black = "We are the Man in black",
    },
    SKIN_NAMES = {
        manutsawee_fuka = "Cosplay",
        manutsawee_jinbei = "Jinbei",
        manutsawee_maid = "Maid",
        manutsawee_miko = "Miko",
        manutsawee_none = "Louis",
        manutsawee_qipao = "Qipao",
        manutsawee_sailor = "Sailor Uniform",
        manutsawee_shinsengumi = "Shinsengumi",
        manutsawee_taohuu = "Taohuu",
        manutsawee_yukata = "Kimono(M) ",
        manutsawee_yukatalong = "Kimono",
        manutsawee_yukatalong_purple = "Kimono(P)",
        manutsawee_uniform_black = "MIB",
    },
    SKIN_QUOTES = {
        manutsawee_fuka = "\"I'm a kung-fu master now.\"",
        manutsawee_jinbei = "\"Relax Feeling good.\"",
        manutsawee_maid = "\"I'm not a maid but i like this.\"",
        manutsawee_miko = "\"Can i fight with yokai?'\"",
        manutsawee_none = "I hate this uniform.",
        manutsawee_qipao = "\"Ni hao ..? Good Fortune'\"",
        manutsawee_sailor = "\"So so so... nothing just say so..\"",
        manutsawee_shinsengumi = "\"One must not infringe the samurai code!\"",
        manutsawee_taohuu = "\"I'm cute, please give me money.\"",
        manutsawee_yukata = "\"Shine omae! haha.'\"",
        manutsawee_yukatalong = "\"Kon ni chi wa ..?'\"",
        manutsawee_yukatalong_purple = "\"こんにちは？'\"",
        manutsawee_uniform_black = "\"\""
    },
}}
