return {
    ACTIONS = {
        CASTSPELL = {
            INSERT = "Insert",
            PULLOUT = "Pull Out",
            SUICIDE = "Suicide",
        },
        MDODGE = "Dash",
        MDODGE2 = "Dodge",
    },
    CHARACTER_ABOUTME = {
        manutsawee = "Manutsawee is too long so just louis.",
    },
    CHARACTER_BIOS = {
        manutsawee = {
            {
                desc = "October 9",
                title = "Birthday",
            },
            {
                desc = "Learn Everything Technical College of Hawaii",
                title = "Current School",
            },
            {
                desc = "Unagi, Bacon and Eggs, Cooked Kelp Fronds, Durian, Roasted durian \nCaliforniaroll, Caviar \nSteamed Ham Sandwich, Tea, Ice Tea \nLiceloaf, Boomberry Pancakes",
                title = "Favorite Food",
            },
            {
                desc = "Manutsawee.",
                title = "Her Past...",
            },
            {
                desc = "The origin of red eye",
                title = "",
            },
            {
                desc = "Tokijin\nThe cursed sword made from the fangs of the Ghost of God is full of evil, and ordinary people can easily be controlled by it.\nIt was originally broken by Sesshomaru, but Louis found it in an abandoned shrine.. .",
                title = "Cursed Sword",
            },
        },
    },
    CHARACTER_DESCRIPTIONS = {
        manutsawee = "*Art of the Japanese sword\n*Brave\n*Benevolent\n*Love to eat",
    },
    CHARACTER_NAMES = {
        manutsawee = "Manutsawee",
    },
    CHARACTER_QUOTES = {
        manutsawee = "\"Where There's a Will, There's a Way\"",
    },
    CHARACTER_SURVIVABILITY = {
        manutsawee = "󰀕Grim",
    },
    CHARACTER_TITLES = {
        manutsawee = "The Red-Eyes Girl",
    },
    M_LOADINGTIPS = {
        TOKIJIN = "\"I can't suppress its evil spirit, I can't control tokijin.\" - L",
        ABIGAIL_TENSEIGA = "\"I'm sorry, Tenseiga can't do anything to save her.\" - L",
        MOMO_REDEYES = "\"That samurai sword sealed countless wronged souls of Yokai and Oni. At the moment it was touched, countless wronged souls sealed in the sword were released. At the same time, they released their demonic power, which gathered into a curse in the eyes of those who touched it. \" - M",
        WICKERBOTTOM_REDEYES = "\"Modern science can't explain why your eyes turn red, and neither can magic.\" - W",
        WAXWELL_REDEYES = "\"I guess your eyes turned red, not from magic, but from a curse, a curse that doesn't belong here.\" - W",
        WOODIE_REDEYES = "\"Like me, cursed?\" - W",
        WILSON_REDEYES = "\"It doesn't matter, nothing is strange here, including this girl with red eyes.\" - W",
        WANDA_REDEYES = "\"emmmm, that's weird, I can't see your past timeline, it's shrouded in a white mist.\" - W",
        WEBBER_REDEYES = "\"Sorry, Miss Louis, I thought you were wearing red contact lenses\" - W",
        WORTOX_REDEYES = "\"Miss, I guess you can see things that we can't see?\" - W",
        WATHGRITHR_REDEYES = "\"Loki has given power to you!\" - W",
    },
    NAMES = {
        BOAT_MSURFBOARD = "Louis's Surf board",
        HARAKIRI = "Harakiri",
        HITOKIRI = "Nihiru",
        HMINGOT = "Hot Mysterious Ingot",
        KATANABLADE = "Katana Blade",
        KATANABODY = "Katana shape",
        KAGE = "Kage",
        KOSHIRAE = "Sakakura",
        MAID_HB = "Louis's headwear",
        MANUTSAWEE = "Manutsawee",
        MFRUIT = "Louis's memory fruit",
        MINGOT = "Mysterious Ingot",
        MMIKO_ARMOR = "Miko Robe",
        MORTALBLADE = "Mortal Blade",
        MSURFBOARD_ITEM = "louis's Surf board",
        M_FOXMASK = "Kitsune Mask",
        M_SCARF = "Black Scarf",
        RAIKIRI = "Raikiri",
        SHINAI = "Shinai",
        SHIRASAYA = "Yasha",
        SHUSUI = "Shusui",
        TENSEIGA = "Tenseiga",
        TOKIJIN = "Tokijin",
        TRUE_HITOKIRI = "Nihiru The Bloodseeker",
        TRUE_KOSHIRAE = "Sakakura The Giant Slayers",
        TRUE_RAIKIRI = "Raikiri The Lightning Cutter",
        TRUE_SHIRASAYA = "Yasha The Demon Slayer",
        VSCODE = "Visual Studio Code",
        YARI = "Yari",
        M_PANTSU = "Blue and white striped pantsu",
        MOMO_HAT = "Erebus Crown",
        MOMO = "Momo",
        MOMOCUBE = "Erebus Cube",
        MOMOAXE = "Erebus(Axe Mode)",
        MOMO_GIFTS = {
            MOMO_GIFT = "Momo gift",
            AGIFTSTOENFROMKLEI = "A gift stolen from Klei",
            ATAKEOUT = "A takeout",
            RESOURCES_COLLECTED_FROM_EVERYWHERE = "Resources collected from everywhere",
            HEALTHY_VEGETABLES = "Healthy vegetables",
            HEALTHY_FURIT = "Healthy fruit",
            AFTERNOON_TEA = "Afternoon tea",
            A_LITTLE_SNACK = "A Little snack",
            FEAST = "A Feast",
            SEAFOOD = "Seafood",
        },
    },
    RECIPE_DESC = {
        HARAKIRI = "Pay your mistake.",
        HITOKIRI = "The Bloodseeker",
        KATANABLADE = "Sharp katana blade",
        KOSHIRAE = "The Giant Slayers",
        MAID_HB = "Louis's headwear set.",
        MINGOT = "Bring it to fire",
        MMIKO_ARMOR = "Miko robe for miko skin",
        MORTALBLADE = "To cut the immortality.",
        MSURFBOARD_ITEM = "louis's Surf board",
        M_FOXMASK = "Fox Mask!",
        M_SCARF = "Black Scarf",
        RAIKIRI = "The Lightning Cutter",
        SHINAI = "Training Sword.",
        SHIRASAYA = "The Demon Slayer",
        SHUSUI = "A Legendary Sword of Wano.",
        TRUE_HITOKIRI = "True Nihiru",
        TRUE_KOSHIRAE = "True Sakakura",
        TRUE_RAIKIRI = "True Raikiri",
        TRUE_SHIRASAYA = "The Demon Slayer",
        VSCODE = "There is nothing that cannot be solved with one line of code.",
        YARI = "It's Japanese Spear.",
        KAGE = "Bring the shadows together.",
    },
    SKILL = {
        COOLDOWN = "Cooldown",
        TIER2_COOLDOWN = "Tier2: Cooldown",
        TIER3_COOLDOWN = "Tier3: Cooldown",
        SKILL_LATER = "Later...",
        MINDPOWER_NOT_ENOUGH = "Not now!\n󰀈: ",
        UNLOCK_SKILL = "[UNLOCK] 󰀍: ",
        HAIRTOOSHORT = "My hair isn't long enough for this.",
        SKILL_CANCEL = "Maybe next time",
        REFUSE_RELEASE = "I don't wanna do this.",
        REJECTED = "It won't collaborate to let me release the move.",
        SKILL1ATTACK = "ICHIMONJI",
        SKILL1START = "ICHI NO KATA!\n󰀈: ",
        SKILL2ATTACK = "HABAKIRI!!",
        SKILL2START = "NI NO KATA!\n󰀈: ",
        SKILL3ATTACK = "ONIKIRI!!",
        SKILL3START = "SAN NO KATA! \n󰀈: ",
        SKILL4ATTACK = "ISSHIN!!",
        SKILL4START = "SHI NO KATA!\n󰀈: ",
        SKILL5ATTACK = "SHINDEN ISSEN!!",
        SKILL5START = "GO NO KATA!\n󰀈: ",
        SKILL6ATTACK = "RYUSEN!!",
        SKILL6START = "ROKU NO KATA!\n󰀈: ",
        SKILL7ATTACK = "SUSANOO!!",
        SKILL7START = "SHICHI NO KATA!\n󰀈: ",
        SKILL8ATTACK = "IMMORTAL SLASH!!!",
        SKILL8START = "IMMORTAL SLASH NO KATA!\n󰀈: ",
        SKILL9ATTACK = "SORYUHA !!!",
        SKILL9START = "SORYUHA NO KATA!\n󰀈: ",
    },
    SKIN_DESCRIPTIONS = {
        lcane = "Would you believe a stick fell from the moon?",
        manutsawee_maid_m = "Maid's outfit",
        manutsawee_bocchi = "Goto Hitori's sportswear from Bocchi The Rock",
        manutsawee_fuka = "Fu hua hawk of the fog's outfit from honkai impact 3d",
        manutsawee_jinbei = "Japan's outfit.",
        manutsawee_maid = "Maid's outfit",
        manutsawee_miko = "Japan's shrine maiden outfit.",
        manutsawee_none = "Thai's school uniform",
        manutsawee_qipao = "China's dress",
        manutsawee_sailor = "Japan's school uniform",
        manutsawee_shinsengumi = "Laws of the Shinsengumi\nOne must not infringe the samurai code\nOne is not authorized to escape from office\nOne is not allowed to arbitrarily raise money\nOne must not arbitrarily handle litigations\nOne is not authorized to engage in personal conflicts\n",
        manutsawee_taohuu = "Vtuber: Taohuu's outfit",
        manutsawee_uniform_black = "Agent's uniform from Men in Black.",
        manutsawee_lycoris = "Takina's outfit from Lycoris Recoil",
        manutsawee_yukata = "Japan's outfit mini version.",
        manutsawee_yukatalong = "Japan's outfit.",
        mnaginata = "Naginata",
    },
    SKIN_NAMES = {
        lcane = "Moon cane",
        manutsawee_maid_m = "Maid",
        manutsawee_bocchi = "Guitar Hero",
        manutsawee_fuka = "Cosplay",
        manutsawee_jinbei = "Jinbei",
        manutsawee_maid = "Maid",
        manutsawee_miko = "Miko",
        manutsawee_none = "Louis",
        manutsawee_qipao = "Qipao",
        manutsawee_sailor = "Sailor Uniform",
        manutsawee_shinsengumi = "Shinsengumi",
        manutsawee_taohuu = "Taohuu",
        manutsawee_uniform_black = "MIB",
        manutsawee_lycoris = "Lycoris",
        manutsawee_yukata = "Kimono(M) ",
        manutsawee_yukatalong = "Kimono",
        mnaginata = "Naginata",
    },
    SKIN_QUOTES = {
        manutsawee_maid_m = "\"Guest sama, would you like a cup of coffee?\"",
        manutsawee_bocchi = "\"mu mu mu mu mu mu mu mu\"",
        manutsawee_fuka = "\"I'm a kung-fu master now.\"",
        manutsawee_jinbei = "\"Relax Feeling good.\"",
        manutsawee_maid = "\"Guest sama, would you like a cup of coffee?\"",
        manutsawee_miko = "\"Can i fight with yokai?'\"",
        manutsawee_none = "I hate this uniform.",
        manutsawee_qipao = "\"Ni hao ..? Happy Lunar New Year!'\"",
        manutsawee_sailor = "\"So so so... nothing just say so..\"",
        manutsawee_shinsengumi = "\"One must not infringe the samurai code!\"",
        manutsawee_taohuu = "\"I'm cute, please give me money.\"",
        manutsawee_uniform_black = "\"It's because the light from Venus is reflected on...the swamp gas...so...\"",
        manutsawee_lycoris = "\"Heart is running away! ! !\"",
        manutsawee_yukata = "\"Shine omae! haha.'\"",
        manutsawee_yukatalong = "\"Kon ni chi wa ..?'\"",
    },
    UI = {
        WORLDGEN = {
            NOUNS = {
                "Louis's pantsu..."
            }
        },
    },
}
