return {
    DESCRIBE = {
        BOAT_MSURFBOARD = "Very exquisite workmanship.",
        HARAKIRI = "This knife look so good.",
        HITOKIRI = "What a weird sword.",
        HMINGOT = "it's very hot!",
        KATANABLADE = "Is it can use without sword-handle?",
        KATANABODY = "so what?",
        KOSHIRAE = "What a beautyful sword.",
        MAID_HB = "It's look good.",
        MFRUIT = "Fruit?",
        MINGOT = "What is this?",
        MMIKO_ARMOR = "Not for me.",
        MNAGINATA = "This spear look different.",
        MORTALBLADE = "To cut the immortality.",
        MSURFBOARD_ITEM = "Which lady's surfboard is this?",
        M_FOXMASK = "What a nice mask!.",
        M_SCARF = "It'll be good for when winter comes.",
        RAIKIRI = "What a beautyful sword.",
        SHINAI = "Is this useful?",
        SHIRASAYA = "What a beautyful sword.",
        SHUSUI = "It's beautiful.",
        TOKIJIN = "I found it at an abandoned shrine near my home.",
        TRUE_HITOKIRI = "What a weird sword.",
        TRUE_KOSHIRAE = "What a beautyful sword.",
        TRUE_RAIKIRI = "This sword look dangerous,Don't touch it.",
        TRUE_SHIRASAYA = "What a beautyful sword.",
        YARI = "This spear look different.",
    },
}
