return {
    DESCRIBE = {
        M_SCARF = "It'll be good for when winter comes.",
        MAID_HB = "It's look good.",
        M_FOXMASK = "What a nice mask!.",
        MMIKO_ARMOR = "Not for me.",
        MFRUIT = "Fruit?",
        MINGOT = "What is this?",
        HMINGOT = "it's very hot!",
        KATANABODY = "so what?",
        HARAKIRI = "This knife look so good.",
        SHINAI = "Is this useful?",
        MKATANA = "It's a sword.",
        MNAGINATA = "This spear look different.",
        YARI = "This spear look different.",
        KATANABLADE = "Is it can use without sword-handle?",
        HITOKIRI = "What a weird sword.",
        TRUE_HITOKIRI = "What a weird sword.",
        KOSHIRAE = "What a beautyful sword.",
        TRUE_KOSHIRAE = "What a beautyful sword.",
        SHIRASAYA = "What a beautyful sword.",
        TRUE_SHIRASAYA = "What a beautyful sword.",
        RAIKIRI = "What a beautyful sword.",
        TRUE_RAIKIRI = "This sword look dangerous,Don't touch it.",
        MSURFBOARD_ITEM = "Which lady's surfboard is this?",
        BOAT_MSURFBOARD = "Very exquisite workmanship.",
        KUROKATANA = "It's beautiful.",
        SHUSUI = "It's beautiful.",
        MORTALBLADE = "To cut the immortality.",
    },
}
