return {
    START_DATING_RELATIONSHIP = {
        TITLE  = "交往",
        BODY   = "与埃里巴斯的女儿交♂往, 你将与她确定一种奇怪的关系, 并且她将保护你, 直到你逃出永恒领域。\n\n确定要开始这个关系吗?",
        OK     = "搞快点!♂",
        CANCEL = "让我再想想。",
    },
    SELECT_REQUEST = {
        TITLE  = "妥协?反抗?",
        BODY   = "将你的记忆交给埃里巴斯的女儿, 答应还是拒绝?",
        OK     = "好, 我答应.",
        CANCEL = "开始♂击剑吧.",
    },
    ONREFUSE = {
        LIST = {
            "Honey, don't make trouble, I don't need this.",
            "I just want something related to you, even memories",
            "Honey, Don't you know what I want?",
        },
        IRRELEVANT = "No, what does this have to do with you? I just want her to give it to me.",
    },
    ONNIGHT = {
        FORHONEY = "Don't worry, honey, I will turn on the light.",
        OFSELF = "Don't worry you can't see me.",
    },
    DIALOGUE = {
        HELLO = {
            "Hi honey, long time no see. Why did you end up in this wasteland?",
            "I'm looking for you all over the world.",
            "Of course don't ask why I'm here, you summoned me here.",
            "Still the same, I want your memory.",
            "",
            "",
            "",
            "",
            "",
            "",
        },
        ACCEPT = {
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        },
        REJECT = {
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        },
        SATISFI = {
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        },
        DEFEATED = {

        },
    },
    COZY_SLEEP = "Honey, did you sleep well last night?"
}
