-- The way to write uncompromising mode is shit

return {
    DREADEYE_SPOOKED = "嘿！ 别这样偷袭我！",
    ANNOUNCE_HARDCORE_RES = "你需要我的帮助！ 还有你的身体...",
    ANNOUNCE_WINONAGEN = "\"我还没有拿到‘把石头放进机器’徽章。\"",
    ANNOUNCE_RATRAID = "老鼠?",
    ANNOUNCE_RATRAID_SPAWN = "为什么现在？！",
    ANNOUNCE_RATRAID_OVER = "这些都是重要的材料！ 我认为...",
    ANNOUNCE_ACIDRAIN = {
        "酸雨?!",
        "噢！好痛！",
        "这雨无非就是麻烦！"
    },
    ANNOUNCE_TOADSTOOLED = "一些不祥的事情在搅动",

    ANNOUNCE_ATTACH_BUFF_LESSERELECTRICATTACK = "闪电！我喜欢!",
    ANNOUNCE_ATTACH_BUFF_ELECTRICRETALIATION = "闪电！我喜欢!",
    ANNOUNCE_ATTACH_BUFF_FROZENFURY = "Brrr...希望这玩意有用.",
    ANNOUNCE_ATTACH_BUFF_VETCURSE = "诅咒? 我好像变得更容易饿了。",
    ANNOUNCE_ATTACH_BUFF_HYPERCOURAGE = "我感觉……我的忧虑解除了。",
    ANNOUNCE_ATTACH_BUFF_LARGEHUNGERSLOW = "暂时的, 我不再感到饥饿了",
    ANNOUNCE_ATTACH_BUFF_KNOCKBACKIMMUNE = "吃了它, 我感觉我胖了500斤",
    ANNOUNCE_ATTACH_BUFF_CALIFORNIAKING = "哎呀，麻烦了……",

    ANNOUNCE_DETACH_BUFF_KNOCKBACKIMMUNE = "瞬间我感觉我身上少了500斤.",
    ANNOUNCE_DETACH_BUFF_HYPERCOURAGE = "持续的时候感觉很好。",
    ANNOUNCE_DETACH_BUFF_LARGEHUNGERSLOW = "我的胃正在恢复正常消化速度。",
    ANNOUNCE_DETACH_BUFF_LESSERELECTRICATTACK = "变身时间结束了",
    ANNOUNCE_DETACH_BUFF_ELECTRICRETALIATION = "变身时间结束了",
    ANNOUNCE_DETACH_BUFF_FROZENFURY = "啊，恢复正常了。",
    ANNOUNCE_DETACH_BUFF_VETCURSE = "结束了! 饥饿诅咒消失了!",
    ANNOUNCE_DETACH_BUFF_CALIFORNIAKING = "这段经历将一直困扰着我。",

    ANNOUNCE_RNEFOG = "外面有东西……有新东西……",
    ANNOUNCE_SNEEZE = "我的天啊！怎么回事.",
    ANNOUNCE_HAYFEVER = "aaaa, 鼻子好痒",
    ANNOUNCE_HAYFEVER_OFF = "啊，清新的空气",
    ANNOUNCE_FIREFALL = {
        "看来这头狮子又学会了新把戏！",
        "烦了，隆隆声越来越厉害了！",
        "大家小心脚下！",
    },
    ANNOUNCE_ROOTING = "啊? 从我脚下冒出来了!",
    ANNOUNCE_SNOWSTORM = "aaaa, 我不想被雪埋了!",
    SHADOWTALKER = {
        "你还记得吗? 那个被你害死的人?",
        "他们一定还在着急的找你吧?",
        "她再也不会回来了",
    },
    VETERANCURSETAUNT = {
        "小孩.....来……靠近点……",
        "一个挑战...",
        "诅咒……拯救……出路……",
    },
    VETERANCURSED = {
        "不……要……回来……继续……",
        "契约……已定……",
        "带来……头骨……",
    },

    CURSED_ITEM_EQUIP = "哎哟！",
    WEBBEDCREATURE = "我想是留着以后用吧。",
    ANNOUNCE_RATSNIFFER_ITEMS = {
        LEVEL_1 = "真是一团糟！是时候清算了！"
    },
    ANNOUNCE_RATSNIFFER_FOOD = {
        LEVEL_1 = "这些过期的食物似乎会引来一些不干净的东西."
    },
    ANNOUNCE_RATSNIFFER_BURROWS = "一只老鼠！两只老鼠！一群老鼠！",
    ANNOUNCE_PORTABLEBOAT_SINK = "我们最好在这件事发生之前找到赶紧走.",
    ANNOUNCE_CHARGE_SUCCESS_INSULATED = "哇哦！我差点触电了。",
    ANNOUNCE_CHARGE_SUCCESS_ELECTROCUTED = "哇哦！我差点触电了。",
    ANNOUNCE_SMOLDER_SPORE_EATEN = "绝对不能吃那玩意。",
    ANNOUNCE_SMOLDER_SPORE_INVENTORY_POP = "卧槽，怎么着火了？",
    ANNOUNCE_UM_NO_TORNADO = "现在气流很小，周围没有龙卷风",

    DESCRIBE = {
        TIDDLESTRANGER_RNE = "来者何人。",
        SPEAKER_SPECTER = "我妈妈要叫我去收衣服了。",
        SPEAKER_RUSTED = "我妈妈要叫我去收衣服了。",
        SPEAKER_BRINE = "我妈妈要叫我去收衣服了。",

        CALIFORNIAKING = "胡辣汤，但好像跟在加州的不太一样？。。。",
        CCTRINKET_DON = "很多字都看不清楚捏，只能认出 \"不要\" 和 \"指引\"这两个字。",
        CCTRINKET_JAZZY = "爵士乐，我欣赏不来。",
        CCTRINKET_FREDDO = "上面只有\"自由\"两个字。",
        UNCOMPROMISING_RAT = "好家伙，比中国南方的老鼠还大。",
        UNCOMPROMISING_RATHERD = "这破地方没有老鼠药，也没有除鼠专家。",
        UNCOMPROMISING_RATBURROW = "这破地方没有老鼠药，也没有除鼠专家。",
        UNCOMPROMISING_WINKYBURROW = "这破地方没有老鼠药，也没有除鼠专家。",
        UNCOMPROMISING_WINKYHOMEBURROW = "这破地方没有老鼠药，也没有除鼠专家。",

        WINKY = {
            GENERIC = "不是真的吧？？？",
            ATTACKER = "我觉得我们需要保持一段距离，我不希望你咬我。",
            MURDERER = "谋杀者。",
            REVIVER = "希望你不会做出什么怪事。",
            GHOST = "她的灵魂依然存在。",
            FIRESTARTER = "卧槽，这大耗子会用火，真成精了。",
        },
        WATHOM = {
            GENERIC = "%s 似乎和他没什么区别。",
            ATTACKER = "%s 把你的弹弓收起来。",
            MURDERER = "我需要时刻握着我的刀。",
            REVIVER = "我们还能合作，%s",
            GHOST = "她遭遇了不幸。",
            FIRESTARTER = "这里不是马戏团，%s？",
        },
        WIXIE = {
            GENERIC = "%s 好像有点不太友善。",
            ATTACKER = "%s 暴力会让你无路可走，",
            MURDERER = "别让我拔刀，%s！",
            REVIVER = "%s 的动机是个谜。",
            GHOST = "我们应该帮助 %s吗？我不太确定。",
            FIRESTARTER = "你怎么能这样？",
        },

        RATPOISONBOTTLE = "毒药，有一股强烈的杏仁味。",
        RATPOISON = "毒药，有一股强烈的杏仁味。",

        MONSTERSMALLMEAT = "看起来只能作为诱饵，绝对不能吃。",
        COOKEDMONSTERSMALLMEAT = "它还是在散发着奇怪的气味。",
        MONSTERSMALLMEAT_DRIED = "emmm，我还是无法下口。",

        UM_MONSTEREGG = "这是？放了半年的鸡蛋？不对。",
        UM_MONSTEREGG_COOKED = "紫色的蛋黄？？？",

        MUSHROOMSPROUT_OVERWORLD = "它似乎正在使用孢子污染空气。",
        TOADLING = "某种寄生虫？",
        UNCOMPROMISING_TOAD = "它看起来病得很厉害，但是好像对它来说没影响。",

        GASMASK = "我可以戴上这个缓解这可怕的过敏症。",
        MOCK_DRAGONFLY = "这家伙自己来找茬了。",
        MOTHERGOOSE = "长着鹿角的鹅？",
        SPIDERQUEENCORPSE = "好恶心啊！",
        VETSITEM = "我不理解的一股力量，黑暗？",
        SCREECHER_TRINKET = "我看不出来这玩意有什么用。",
        UM_SAND = "一堆珊瑚礁、贝壳、石英的碎屑。",
        UM_SANDHILL = "一小堆沙子而已。",
        SNOWPILE = "我需要赶紧处理掉这堆雪，不然会有麻烦。",
        SNOWGOGGLES = "能让我在暴风雪中保持头部温暖，还能看清前方的路。",
        SNOWMONG = "我就说吧，麻烦来了。",
        SHOCKWORM = "它和雷切一样带电？！",
        ZASPBERRY = "这个蓝莓吃完嘴有点麻。",
        ZASPBERRYPARFAIT = "吃起来嘴有点麻的甜点。",
        ICEBOOMERANG = "我应该戴着手套，",
        MINOTAUR_BOULDER = "危险！不要动它。",
        MINOTAUR_BOULDER_BIG = "勾引那个大角犀牛去撞这个大石头。",
        BUSHCRAB = "啊啊啊！它是怎么出现在我面前的？！",
        LAVAE2 = "谁有烤箱手套，这个太烫了！",
        DISEASECUREBOMB = "很难闻，但是这个油可以给植物治病，还没有副作用。",
        TOADLINGSPAWNER = "噫，好难闻的味道。",
        SNOWBALL_THROWABLE = "有谁想打雪仗呀？",
        VETERANSHRINE = "头骨，我好害怕。",
        WICKER_TENTACLE = "它要被分解了。",
        HONEY_LOG = "甜，但是有点甜过头。",
        RAT_TAIL = "啊啊啊，我不想碰这个尾巴，好恶心。",
        PLAGUEMASK = "奇怪的造型，好像在某本漫画上看到过。",
        SALTPACK = "把盐粒撒在雪上，降低雪的融点，让雪融化得更快。",
        SPOREPACK = "好脏，不能把物品放在里面。",
        SPIDER_TRAPDOOR = "守株待兔。",
        TRAPDOOR = "这里面肯定藏了危险的东西，比如蜘蛛。",
        HOODEDTRAPDOOR = "这里面肯定藏了危险的东西，比如蜘蛛。",
        SHROOM_SKIN_FRAGMENT = "毫无用处，还散发出非常刺鼻的味道。",
        AIR_CONDITIONER = "它明明是用非常刺鼻的蛤蟆皮做的，但是居然能过滤掉附近空气中的污染物。",
        UM_SCORPION = "蝎子，它是某种沙漠分类中的物种，但是比我在书中看到的还要大？！",
        UM_SCORPIONHOLE = "估计是蝎子的巢穴。",
        SCORPIONCARAPACE = "它能用来作为诱饵，但是不能作为食物。",
        SCORPIONCARAPACECOOKED = "我就是饿死我也不会吃这个。",
        HARDSHELLTACOS = "再来点沙拉酱？\n 啊，中国的街头小吃！我多么想念你....",
        SKELETONMEAT = "赶紧扔掉！！！！！！！！！！！！！！！！！！！",
        -- CHIMP = "",
        SWILSON = "复制品，傀儡，妖怪人形。",
        VAMPIREBAT = "让开！我要把它一刀两断。",
        CRITTERLAB_REAL = "卡哇伊，谁是可爱的小家伙？",
        CRITTERLAB_REAL_BROKEN = "我要把它修好，作为一个迷你动物收容所。",
        CHARLIEPHONOGRAPH_100 = "这玩意没有电源，怎么运行的？",
        WALRUS_CAMP_SUMMER = "看起来有人在这里扎过营，但是我能确定它的主人绝对不友好。",
        RICEPLANT = "WOW.水稻诶！在中国和日本的农村经常能看到。",
        RICE = "要把它们煮过才好吃。",
        RICE_COOKED = "有点煮过头了好像，有点硬。\n 我想做成饭团，那样很好吃。",
        SEAFOODPAELLA = "我还要再来一碗！",
        STUMPLING = "树桩？在动？还会打人，卧槽。",
        -- BIRCHLING = "",
        BUGZAPPER = "啪！啪！啪！讨厌的虫子。",
        MOON_TEAR = "这块石头？在流泪？",
        SHADOW_TELEPORTER = "巨大的诱惑？但是不好意思，我对这种东西不感兴趣。",
        POLLENMITEDEN = "离远点，这种螨虫会引起强烈的过敏症状。",
        POLLENMITES = "啊啊啊啊啊啊啊，离我远点！！！！！！",
        SHADOW_CROWN = "戴着它，我感觉有点不舒服。。。",
        RNEGHOST = "孤魂野鬼，它还在怨念着什么？",
        LICELOAF = "吃起来非常酥脆。在中国四川吃过这个。",
        SUNGLASSES = "很酷，不说话。",
        TRAPDOORGRASS = "那下面一定藏着危险。",
        LUREPLAGUE_RAT = "我不想再看它一眼，赶紧把它切了。",
        MARSH_GRASS = "没有任何动静，看起来那里面很安全？",
        CURSED_ANTLER = "是那大家伙自己找上门来的，而且还败给了我。\n 还有它这个角，有点重。",
        BERNIEBOX = "看起来是那个玩火的女孩子的物品，帮她保管一下吧。",
        HOODED_FERN = "地面上有阳光，它能长这么大。",
        HOODEDWIDOW = "一只巨大的蜘蛛在我面前，我的雷切在抖动，好像是在想告诉我什么。",
        GIANT_TREE = "我在老远就看到这些巨大的红衫了，但是它们看起来不太对劲？",
        ANCIENTHOODEDTURF = "铺回去吧，没什么用。",
        HOODEDMOSS = "这块地皮上，好像有月光？",
        WIDOWSGRASP = "那只大蜘蛛的爪子，可以划开那些茧。",
        WEBBEDCREATURE = "不用想，那只大蜘蛛肯定抓了很多生物。",
        SNAPDRAGON_BUDDY = "它让我想起来了捕蝇草。",
        SNAPDRAGON = "金鱼草，但是它为什么会发出牛的叫声？",
        SNAPPLANT = "hentai发育。",
        WHISPERPOD = "把它种下去吧，这样它才能生长。",
        WHISPERPOD_NORMAL_GROUND = {
            GENERIC = "没种过这种植物，我不知道它具体需要什么，但是它需要种子。",
            GROWING = "就是这样，再多一些...",
        },
        FRUITBAT = "更丑了，一只蓝莓果蝠。",
        PITCHERPLANT = "猪笼草，它会捕食这附近自投罗网的虫子",
        APHID = "这群蚜虫啃食着那些红衫。",
        NYMPH = "它正在将瘟疫传播到更多的树木上。",
        GIANT_TREE_INFESTED = "这棵红衫被那些害虫感染了，正在慢慢地死去。",
        GIANT_BLUEBERRY = "可以做成蓝莓酱吗？",
        STEAMEDHAMS = "汉堡包！",
        BLUEBERRYPANCAKES = "我可以吃三份吗？",
        DEVILSFRUITCAKE = "甜的有点邪恶。",
        SIMPSALAD = "有时候，也可以吃点蔬菜，减减肥。",
        BEEFALOWINGS = "多余的牛角，我直接吃派。",
        WIDOWSHEAD = "啊啊啊，我不要戴上这个，快拿走。",
        -- HOODED_MUSHTREE_TALL = "",
        -- HOODED_MUSHTREE_MEDIUM = "",
        -- HOODED_MUSHTREE_SMALL = "",
        WATERMELON_LANTERN = "实不相瞒，我更想切开吃掉它。",
        SNOWCONE = "什么味道都没有，只是单纯的雪。",
        VIPERWORM = "它身上流着黑黑的东西，是什么东西？",
        VIPERFRUIT = "看起来有点像草莓。",
        VIPERJAM = "这果酱，能做吐司吗？",
        BLUEBERRYPLANT = {
            READY = "哇哦！ 这里的一切都很大！",
			FROZE = "它冻住了，干净利落！",
			REGROWING = "它会回来的，对吗？",
		},
        BERNIE_INACTIVE = {
            BROKEN = "我没有带针线包。",
            GENERIC = "完全烧焦了。",
            ASHLEY_BROKEN = "我没有带针线包。",
            ASHLEY = "完全烧焦了。",
        },
        BERNIE_ACTIVE = {
            GENERIC = "那只泰迪熊在动！",
            ASHLEY = "那只泰迪熊在动！"
        },
        BERNIE_BIG = {
            GENERIC = "它既令人毛骨悚然又可爱！",
            ASHLEY = "它既令人毛骨悚然又可爱！"
        },
        MAGMAHOUND = "一只石化的狗？它嘴里冒着火！",
        LIGHTNINGHOUND = "镀金的狗？还带电...",
        SPOREHOUND = "它被真菌寄生了.",
        GLACIALHOUND = "被人施加了寒冰魔法.",
        RNESKELETON = "不不不, 我不想与你共舞.",
        RAT_WHIP = "老鼠的尾巴做成的鞭子, 这不是一个好主意....",
        KLAUS_AMULET = "这就是\"圣诞\"老人复活用的。",
        CRABCLAW = "里面全是石头，没有肉.",
        HAT_RATMASK = "我不想戴上这个面具，一点都不想.",
        ORANGE_VOMIT = "呕，我要吐了",
        GREEN_VOMIT = "呕，我要吐了",
        RED_VOMIT = "呕，我要吐了",
        PINK_VOMIT = "呕，我要吐了",
        YELLOW_VOMIT = "呕，我要吐了",
        PURPLE_VOMIT = "呕，我要吐了",
        PALE_VOMIT = "呕，我要吐了",
        PIGKING_PIGGUARD = "这些猪确实知道如何玩得开心。",
        PIGKING_PIGTORCH = "这些猪确实知道如何玩得开心。",
        BIGHT = "制造者的干预，后果已经实现。",
        KNOOK = "这真是令人毛骨悚然！",
        ROSHIP = "怨念唤醒了它，看起来很渴望鲜血，溜，赶紧溜，快溜.",
        UM_PAWN = "走，快走，不要靠近它",
        UM_PAWN_NIGHTMARE = "走，快走，不要靠近它.",
        UNCOMPROMISING_BLOWGUN = "这才对嘛",
        BLOWGUNAMMO_TOOTH = "这才对嘛",
        BLOWGUNAMMO_FIRE = "这才对嘛",
        BLOWGUNAMMO_SLEEP = "这才对嘛",
        BLOWGUNAMMO_ELECTRIC = "这才对嘛",
        ANCIENT_AMULET_RED = "不，为了她，我不会的",
        UM_BEAR_TRAP = "偷猎者设置的陷阱，但是在这里不像是用来捕猎的。",
        UM_BEAR_TRAP_OLD = "偷猎者设置的陷阱，但是在这里不像是用来捕猎的。",
        UM_BEAR_TRAP_EQUIPPABLE_TOOTH = "偷猎者设置的陷阱，但是在这里不像是用来捕猎的。",
        UM_BEAR_TRAP_EQUIPPABLE_GOLD = "偷猎者设置的陷阱，但是在这里不像是用来捕猎的。",
        CORNCAN = "嗯，里面装了玉米。",
        SKULLCHEST_CHILD = "我可以钻进去试试吗？",
        SLOBBERLOBBER = "一种将任何东西化为灰烬的野蛮方式。",
        GORE_HORN_HAT = "它将阴影变成速度！",
        BEARGERCLAW = "整个永恒大陆都挖了.",
        FEATHER_FROCK = "思必得！",
        REDGEM_CRACKED = "好漂亮呀！",
        BLUEGEM_CRACKED = "啊，这个好丑",
        ORANGEGEM_CRACKED = "它会让你的手指发麻。",
        GREENGEM_CRACKED = "这个感觉真的很轻。",
        YELLOWGEM_CRACKED = "它闪闪发光.",
        PURPLEGEM_CRACKED = "诡异",
        OPALPRECIOUSGEM_CRACKED = "它闪闪发光，令人着迷",
        RED_MUSHED_ROOM = "呕，我要吐了",
        GREEN_MUSHED_ROOM = "呕，我要吐了",
        BLUE_MUSHED_ROOM = "呕，我要吐了",
        SKULLFLASK = "暂时忘记悲伤, 恐惧......",
        SKULLFLASK_EMPTY = "悲伤, 恐惧又来回来了。",
        STANTON_SHADOW_TONIC = "喝了这个没有什么好处……",
        STANTON_SHADOW_TONIC_FANCY = "优雅，但是喝了一样没有什么好处……",
        STANTON = "对不起，我不喝酒",
        ARMORLAVAE = "为什么我们不能成为朋友？",
        THEATERCORN = "要是我们能有一些电影节目来配合就好了。",
        DEERCLOPS_BARRIER = "放我出去！",
        MOONMAW_DRAGONFLY = "啊啊啊！！你是什么东西！",
        MOONMAW_LAVAE = "活的玻璃块",
        SNAPPERTURTLE = "哈哈，真是有趣的动物。",
        SNAPPERTURTLEBABY = "哈哈，真是有趣的动物。",
        SNAPPERTURTLENEST = "海龟的潮湿巢穴",
        GLASS_SCALES = "光芒四射，而且相当锐利。",
        MOONGLASS_GEODE = "带电的玻璃一旦破裂就不会持续太久。",
        ARMOR_GLASSMAIL = "这个太酷了！！",
        ARMOR_GLASSMAIL_SHARDS = "这个太酷了！！",
        MOONMAW_GLASSSHARDS_RING = "这个太酷了！！",
        MOONMAW_GLASSSHARDS = "这个太酷了！！",
        MOONMAW_LAVAE_RING = "活的玻璃块",
        MUTATOR_TRAPDOOR = "这个好像是给蜘蛛吃的",
        WOODPECKER = "我以前到处都看到他们出去迁徙旅行！",
        SNOTROAST = "沃比想吃这个吗？",
        BOOK_RAIN_UM = "它篡改了当地云层的气球。",
        FLORAL_BANDAGE = "仙人掌花的药用特性与药膏非常相配。",
        DORMANT_RAIN_HORN = "少了什么, 不起作用？",
        RAIN_HORN = "我的记忆一定很模糊。我以为这做了别的事情。",
        DRIFTWOODFISHINGROD = "一种更稳定的钓鱼方式.",
        PIED_RAT = "卖唱的，引来的不是人而是老鼠.",
        PIED_PIPER_FLUTE = "我演奏它，会引来老鼠吗？",
        UNCOMPROMISING_PACKRAT = "偷东西就算了，怎么还带包呢？",
        WINONA_TOOLBOX = "我想知道里面是什么样的小玩意和吻痕。",
        WINONA_CATAPULT_ITEM = "我以前在中国旅行的时候学习过手工，应该可以应付。",
        WINONA_SPOTLIGHT_ITEM = "我以前在中国旅行的时候学习过手工，应该可以应付。",
        WINONA_BATTERY_LOW_ITEM = "我以前在中国旅行的时候学习过手工，应该可以应付。",
        WINONA_BATTERY_HIGH_ITEM = "我以前在中国旅行的时候学习过手工，应该可以应付。",
        POWERCELL = "电池，但是电哪里来呢？",
        WINONA_UPGRADEKIT_ELECTRICAL = "让那些设备提升工作效率。",
        OCEAN_SPEAKER = "什么玩意",
        OCUPUS_BEAK = "克拉肯的嘴，它会吐出一种奇怪的液体。",
        OCUPUS_TENTACLE = "在韩国，有些人喜欢生吃，呃，我不喜欢就是了",
        OCUPUS_TENTACLE_EYE = "嗯，我能用这个做什么？",
        OCUPUS_TENTACLE_COOKED = "我需要一些芥末。",
        UM_OCUPUS_EYE = "不要",
        UM_OCUPUS_EYETACLE = "我们不是你的食物！",
        UM_OCUPUS_TENTACLE = "来自海洋的武器。",
        UM_OCUPUS_BEAK = "监视者想让我们一直留在这里。",
        BEAKBASHER = "我把喙放在棍子上。现在怎么办？",
        HOUNDIOUS_OBSERVIOUS = "它还活着！",
        ARMOR_REED_UM = "该下地干活了.",
        ARMOR_SHARKSUIT_UM = "这让我感觉自己是食物链顶端的人。",
        ROCKJAWLEATHER = "好漂亮的鳍。",
        EYEOFTERROR_MINI_ALLY = "我开始感到不自在了。",
        STUFFED_PEEPER_POPPERS = "连食物都在看着我。",
        UM_DEVILED_EGGS = "如果我没煮了它，那它会孵化出来什么呢？",
        LUSH_ENTRANCE = "从下面传来一股非常浓烈的香味。",
        CRITTER_FIGGY = "棉花虫子？",
        GIANT_TREE_BIRDNEST = "掉下来居然没摔碎？Σ(っ °Д °;)っ",
        SLUDGE = "一团有臭味的东西？我们弄这些有什么用？",
        SLUDGE_OIL = "啊？海泥油？",
        CANNONBALL_SLUDGE_ITEM = "它还是把事情搞砸了。",
        BOAT_BUMPER_SLUDGE = "它会反弹任何击中它的东西。",
        BOAT_BUMBER_SLUDGE_KIT = "一个更柔软的垫子，可以用来对付撞到我船的东西。",
        UM_AMBER = "琥珀！",
        UM_BEEGUN = "胡蜂枪诶",
        BULLETBEE = {
            GENERIC = "我喜欢那只蜜蜂臂的剪裁。",
            HELD = "Buzz!",
        },
        CHERRYBULLETBEE = {
            GENERIC = "我喜欢那只蜜蜂臂的剪裁。",
            HELD = "Buzz!",
        },
        SUNKENCHEST_ROYAL_RANDOM = "光是得到这个就太痛苦了。",
        SUNKENCHEST_ROYAL_RED = "光是得到这个就太痛苦了。",
        SUNKENCHEST_ROYAL_BLUE = "光是得到这个就太痛苦了。",
        SUNKENCHEST_ROYAL_PURPLE = "光是得到这个就太痛苦了。",
        SUNKENCHEST_ROYAL_GREEN = "光是得到这个就太痛苦了。",
        SUNKENCHEST_ROYAL_ORANGE = "光是得到这个就太痛苦了。",
        SUNKENCHEST_ROYAL_YELLOW = "光是得到这个就太痛苦了。",
        SUNKENCHEST_ROYAL_RAINBOW = "光是得到这个就太痛苦了。",
        STEERINGWHEEL_COPPER = "它可以持续一千年。",
        STEERINGWHEEL_COPPER_ITEM = "我们首先需要一些东西来引导。",
        BOAT_BUMPER_COPPER = "这应该持续足够长的时间。",
        BOAT_BUMPER_COPPER_KIT = "现在我们只需要一艘船来保护。",
        UM_DREAMCATCHER = "你梦中的电子羊是什么颜色？",
        UM_BRINEISHMOSS = "苔藓，到处都是。",
        UM_COALESCED_NIGHTMARE = "更纯粹的噩梦。",
        SLUDGE_CORK = "这应该可以加快处理污泥的速度。",
        SLUDGESTACK = "随着时间的推移，污泥已经磨损了岩石。",
        SPECTER_SHIPWRECK = "一切终将毁灭。",
        UNCOMPROMISING_HARPOON = "远距离刺伤从未如此简单。",
        UNCOMPROMISING_HARPOON_HEAVY = "它没有看起来那么重。",
        UNCOMPROMISING_HARPOONREEL = "这是卷轴交易。",
        UM_MAGNERANG = "磁铁不是我的专长。",
        UM_MAGNERANGREEL = "它看起来不稳定。",
        SIREN_THRONE = "哦，看！一块石头！不管怎样。",
        LAVASPIT_SLUDGE = "一堆岩浆。",
        UM_BEEGUARD_SHOOTER = "蓬松飞起来！",
        UM_BEEGUARD_SEEKER = "蓬松飞起来！",
        UM_BEEGUARD_BLOCKER = "不能正面应对。",
        PORTABLEBOAT_ITEM = "很小，方便，软软的浮船，但是不安全",
        MASTUPGRADE_WINDTURBINE_ITEM = "永动机，无限循环",
        UM_ORNAMENT_OPOSSUM = "它会是一个很好的装饰吗？可能！",
        UM_ORNAMENT_RAT = "它会是一个很好的装饰吗？可能！",
        TRINKET_WATHOM = "这是……宝藏？我想？是吗？？",
        CODEX_MANTRA = "会成为一个很棒的睡前故事......用于噩梦！",
        WIXIE_PIANO = "这跟学校里的钢琴不太一样啊....",
        WIXIE_CLOCK = "我无法打开它。",
        WIXIE_WARDROBE = "等等，这已经在这里多久了？",
        CHARLES_T_HORSE = "看不到一个齿轮。",
        THE_REAL_CHARLES_T_HORSE = "看不到一个齿轮。",
        SLINGSHOT_MATILDA = "子弹要投掷。",
        SLINGSHOT_GNASHER = "子弹要投掷。",
        SLINGSHOTAMMO_LAZY = "子弹要投掷。",
        SLINGSHOTAMMO_SHADOW = "子弹要投掷。",
        SLINGSHOTAMMO_FIRECRACKERS = "子弹要投掷。",
        SLINGSHOTAMMO_HONEY = "子弹要投掷。",
        SLINGSHOTAMMO_RUBBER = "子弹要投掷。",
        SLINGSHOTAMMO_TREMOR = "子弹要投掷。",
        SLINGSHOTAMMO_MOONROCK = "子弹要投掷。",
        SLINGSHOTAMMO_MOONGLASS = "子弹要投掷。",
        SLINGSHOTAMMO_SALT = "子弹要投掷。",
        SLINGSHOTAMMO_SLIME = "子弹要投掷。",
        SLINGSHOTAMMO_GOOP = "子弹要投掷。",
        SLINGSHOTAMMO_LIMESTONE = "子弹要投掷。",
        SLINGSHOTAMMO_TAR = "子弹要投掷。",
        SLINGSHOTAMMO_OBSIDIAN = "子弹要投掷。",
        BAGOFMARBLES = "我欣赏他们设计的复杂性。",
        MEATRACK_HAT = {
            GENERIC = "我想挂点肉！",
            DRYING = "来吧，肉已经干了！",
            DRYINGINRAIN = "忘记下雨吧！ 干燥！",
            DRYINGINRAIN_NOTMEAT = "忘记下雨吧！ 干燥！",
            DRYING_NOTMEAT = "这东西要多久才能干？！",
        },
        FISHMEAT_DRIED = "大鱼干，熬汤很好喝。",
        SMALLFISHMEAT_DRIED = "鱼干，熬汤很好喝。",
        WIXIEGUN = "以前在夏威夷学过枪法。",
        MARA_BOSS1 = "它不属于这里，呃，在哪都不应该存在。",
        UM_PYRE_NETTLES = "好吧，那个肯定有毒。",
        UM_SMOLDER_SPORE = "如果我不磨蹭的话，我可以溜过去。",
        UM_ARMOR_PYRE_NETTLES = "贴近一点都是热的",
        UM_BLOWDART_PYRE = "无情。有效。",
        ALPHA_LIGHTNINGGOAT = "小心！很危险。它...天生带电。",
        UM_TORNADO = "强烈的气流聚集起来，形成了这个庞然大物，赶紧溜。",
        UM_WATERFALL = "当你需要一双雨鞋时，它们在哪里？",
    }
}
