return {
    ANNOUNCE_LNCOMPREHENSIBLE = "",
    DESCRIBE = {
        BOAT_MSURFBOARD = "",
        HARAKIRI = "",
        HITOKIRI = "",
        HMINGOT = "",
        KATANABLADE = "",
        KATANABODY = "",
        KOSHIRAE = "",
        MAID_HB = "",
        MFRUIT = "",
        MINGOT = "",
        MMIKO_ARMOR = "",
        MORTALBLADE = "",
        MSURFBOARD_ITEM = "",
        M_FOXMASK = "",
        M_SCARF = "",
        RAIKIRI = "",
        SHINAI = "",
        SHIRASAYA = "",
        SHUSUI = "",
        TOKIJIN = "",
        TRUE_HITOKIRI = "",
        TRUE_KOSHIRAE = "",
        TRUE_RAIKIRI = "",
        TRUE_SHIRASAYA = "",
        VSCODE = "",
        YARI = "",
        M_PANTSU = "",
        MOMO_HAT = "",
        MOMO = "",
        MOMOCUBE = "",
        MOMOAXE = "",
        TENSEIGA = "",
        DREADSTONE_STACK_TOMB = "",
    },
}
